# -*- coding: utf-8 -*-
"""AgencyNameLabel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bDRR2jy6WPq_kEwQubEAYhUaWvLyHWZZ
"""

# import library
from google.colab import files
import pandas as pd
import numpy as np
import re

# upload file into google colab
uploaded_file = files.upload()
file = next(iter(uploaded_file))

df = pd.read_excel(file)

# Define the regular expression pattern
pattern = r'\b(Startek|UTS)\b'

# Extract the last word using regular expressions
df['Last_Word'] = df['Campaign: Campaign Name'].str.extract(r'(\w+)\s*$')

# Handle NaN values by replacing them with an empty string
df['Last_Word'] = df['Last_Word'].fillna('')

# Check if the last word matches the pattern
mask = df['Last_Word'].str.contains(pattern, case=False, regex=True, na=False)

# Assign labels to the 'Agency_Name' column based on the pattern match
df.loc[mask, 'Agency_Name'] = df.loc[mask, 'Last_Word']
df.loc[~mask, 'Agency_Name'] = 'UTS'

# Drop the 'Last_Word' column if it's no longer needed
df = df.drop('Last_Word', axis=1)

# rename file with new name
current_filename = file[:-5]
output_file = f'Updated {current_filename}.xlsx'

# save to excel and download
df.to_excel(output_file, index = False)
files.download(output_file)